### ISSUE TITLE
Suggestion to put information/remark on where your data may have been used in the readme file

### ISSUE THREAD

**Issue by psyntium** [CITF-Malaysia/citf-public#7]
For example:
- https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/country_data/Malaysia.csv

This will be useful for us to help to compare the data with other countries as well and perhaps improve the data structure to be more standardised

If CDC is using this data as well, that'll be great too.

**Comment by psyntium** [comment]
created a pull-request:
https://github.com/CITF-Malaysia/citf-public/pull/8

**Comment by CITF-Malaysia** [comment]
We considered this suggestion quite carefully, but have decided against it, simply because we don't want to commit to maintaining what looks to be a very dynamic list. As of now, at least 2 international sites (OWiD and FT) and several Malaysia-based sites/devs have pointed to our repo; we expect this list to grow as we expand our reach and add more datasets.
